#!/bin/sh
if cygpath -w / >/dev/null 2>/dev/null; then
  CLASSPATH="hsqldb.jar;jfreechart-1.0.13.jar;jcommon-1.0.16.jar;oscilloscope.jar;$CLASSPATH"
else
  CLASSPATH="hsqldb.jar:jfreechart-1.0.13.ja:jcommon-1.0.16.jar:oscilloscope.jar:$CLASSPATH"
fi
java Oscilloscope
